#!/usr/bin/env zsh

function ppprint() { print $1 | lolcat }
function ppppprint() { print $1 | figlet -f big | lolcat -a }

function repos() {
  for repo in $HOME/qf/*; do
    ppprint "git pull in ${repo:t}…"
    cd $repo
    git pull --prune
  done
}

function brews() {
  ppprint "brew update >>= upgrade >>= cleanup…"
  brew update && brew upgrade && brew cleanup && brew cask cleanup
}

function rusts() {
  ppprint "rustup update >>= reinstall cargo-clippy"
  rustup update
  if [ $? -ne 0 ]; then
    cargo +nightly install --force clippy
  fi
}

function stacks() {
  ppprint "stack update…"
  stack update
}

function pips() {
  ppprint "pip3 update >> pip_pypy3 update…"
  for pip in 'pip3' 'pip_pypy3'; do
    $pip list --outdated --format=freeze | \
      cut -d = -f 1 | \
      parallel "$pip install -U {}"
  done
}

repos; brews; rusts; stacks; pips; ppppprint "DONE!"
