#!/usr/bin/env zsh

function ppprint() { print $1 | lolcat }
function ppppprint() { print $1 | figlet -f big | lolcat -a }

for repo in $HOME/qf/*; do
  ppprint "git pull in ${repo:t}…"
  cd $repo
  git pull --prune
done

ppprint "brew update >>= upgrade >>= cleanup…"
brew update && brew upgrade && brew cleanup && brew cask cleanup

ppprint "rustup update >> reinstall cargo-clippy…"
rustup update
cd $HOME/github/rust-clippy
git pull --prune
cargo update
cargo install --force

ppprint "stack update…"
stack update

ppprint "pip3 update >> pip_pypy >> pip_pypy3 update…"
for pip in 'pip3' 'pip_pypy' 'pip_pypy3'; do
  $pip list --outdated --format=freeze | cut -d = -f 1 | parallel "$pip install -U {}"
done

ppppprint "DONE!"
