#!/usr/bin/env zsh

print "ssh initialization…"
ssh-init

for repo in $HOME/qf/*; do
  print "git pull in ${repo:t}…"
  cd $repo
  git pull --prune
done

print "brew update => upgrade => cleanup…"
brew update && brew upgrade && brew cleanup && brew cask cleanup

print "rustup update => reinstall cargo-clippy…"
rustup update
cd $HOME/github/rust-clippy
git pull --prune
cargo update
cargo install --force

print "stack update…"
stack update

print "DONE!"
